[platformio]
default_envs = esp32-s3-inverter

[env:esp32-s3-inverter]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1

    -DUSER_SETUP_LOADED
    -DST7789_DRIVER

    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240

    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=9
    -DTFT_RST=8

    -DTFT_RGB_ORDER=TFT_BGR
    -DTFT_INVERSION_ON

    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4

    -DSPI_FREQUENCY=20000000

lib_deps =
    bodmer/TFT_eSPI
